### ISSUE TITLE
Identify Key Components

### ISSUE THREAD

**Issue by 0x4007** [ubiquibot/.github#3]
### 1. Identify Key Components

Start by listing all the major components of your system. This includes:

- **Repositories**: Each repository's purpose and the main technology or language used.
- **Services**: Any internal or external services your system interacts with.
- **Databases**: The types of databases used and their relationships to other components.
- **External Integrations**: Third-party services or APIs your system relies on.
- **Infrastructure**: The underlying infrastructure, such as cloud services, container orchestration (e.g., Kubernetes), and network architecture.

**Comment by chris-chris** [comment]
@pavlovcik 
I'll take this task. It is very important to understand and organize the clean architecture of the system.
Where do you want me to write this document?

- this .github repo?
- another repo for the `docs`?

**Comment by pavlovcik** [comment]
> /start

We have a bug with the bot. Be sure to first set your wallet with /wallet 0x00 and then try /start

**Comment by chris-chris** [comment]
@pavlovcik Should it be an ethereum wallet? which mainnet are you using?

**Comment by chris-chris** [comment]
Oh time limit is just an hour haha

**Comment by pavlovcik** [comment]
Its okay we usually let a few day grace period anyways.
